version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/webapp

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file

hooks:
  BeforeInstall:
   - location: ./codedeploy/cleanup.sh
     timeout: 180
     runas: ubuntu
  AfterInstall:
   - location: ./codedeploy/dependencies.sh
     timeout: 180
     runas: ubuntu
  ApplicationStart:
   - location: ./codedeploy/start.sh
     timeout: 180
     runas: ubuntu