# This is a basic workflow to help you get started with Actions

name: CI

env:
  ARTIFACT_NAME: csye6225-webapp-${{ github.sha }}.zip
  AWS_REGION: us-west-2
  CODEDEPLOY_APPLICATION_NAME: csye6225webapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225webapp

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd ..
          pwd
          ls -al
          mkdir codedeploy_artifact
          zip -r ${{ env.ARTIFACT_NAME }} webapp
          pwd
          ls -al
          mv ${{ env.ARTIFACT_NAME }} codedeploy_artifact/
          pwd
          ls -al
          cd codedeploy_artifact
          pwd
          ls -al
          cd ..
          pwd
          ls -al
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Configure AWS crednetials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Copy Artifact to S3
        run: |
          pwd
          aws s3 sync ../codedeploy_artifact s3://${{ secrets.S3_CODEDEPLOY_BUCKET }}

